version: '3.8'

services:
  energylink:
    build: .
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    network_mode: host  # Wichtig: Damit die App im LAN die Wallbox per UDP erreichen kann
